defaults:
  - _self_
  - base

data:
  num_res_batch_size: 500_000
  batch_size: 128
  coordinate_scaling: 0.1
  min_sequence_size: 50
  max_sequence_size: 64

model:
  node_embed_size: 64
  edge_embed_size: 64
  dropout: 0.0
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: ${model.node_embed_size}
    c_skip: 32
    no_heads: 4
    no_qk_points: 8
    no_v_points: 8
    seq_tfmr_num_heads: 2
    seq_tfmr_num_layers: 2
    num_blocks: 2
    coordinate_scaling: ${data.coordinate_scaling}

experiment:
  debug: False
  wandb:
    name: local_rot_loss_05
    project: se3_flow_matching
    tags: ['local']
  optimizer:
    lr: 0.001

