# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    conda env create -f fm.yml 

    # Activate environment
    conda activate fm_os
     
    # Manually need to install torch-scatter.
    pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cu117.html

    # Install local package.
    # Current directory should be flow-matching/
    pip install -e .
  displayName: 'Install dependencies'
