# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base

inference:
  name: scope_ts_10_ode
  gpu_id: null  # CUDA GPU to use
  seed: 123

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN/
  output_dir: ./inference_outputs/

  # Path to model weights.
  # weights_path: ./weights/paper_weights.pth
  weights_path: /data/rsg/chemistry/jyim/projects/flow-matching/se3_diffusion/weights/scope_weights.pth

  diffusion:
    # Number of steps.
    num_t: 100
    # Analogous to sampling temperature.
    noise_scale: 1.0
    # Final t.
    min_t: 0.01
    use_sde: False

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 60
    # Maximum sequence length to sample.
    max_length: 128
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 1
