description: Base experiment for SE(3) flow matching.

target:
 service: aml
 name: v100

code:
  local_dir: $CONFIG_DIR/../../../../../
  ignore:
    - materials
    - matkin
    - vasp
    - timewarp
    - foundation_3d_encoder
    - sampling/experimental/jyim/se3_flow_matching/wandb/
    - sampling/experimental/jyim/se3_diffusion/weights/
    - sampling/experimental/jyim/se3_flow_matching/dev/
    - '*.ipynb'
    - '*.ckpt'
    - '*.gif'
    - '*.pdb'
    - '*.data'
    - '*.xyz'

storage:
  data_store:
    storage_account_name: feynman0storage
    container_name: simulated-data
    mount_dir: /mnt/feynman0storage_cache/simulated-data
    local_dir: $HOME/feynman0storage_cache/simulated-data

environment:
  registry: msrmoldyn.azurecr.io
  image: feynman:sampling-latest
  username: msrmoldyn
  setup:
    - pip install --user -e sampling/experimental/jyim/se3_flow_matching/.
    - pip install ml-collections
    - pip install dm-tree
    - pip install wandb
    - pip install hydra-core --upgrade


jobs:
- name: "test_run"
  sku: G1
  process_count_per_node: -1
  submit_args:
    env:
      PYTHONPATH: .
  command:
  - echo "output_dir=$$AMLT_OUTPUT_DIR"
  - python sampling/experimental/jyim/se3_flow_matching/experiments/train_se3_flows.py --config-name local
