defaults:
  - base
  - _self_

data:
  sampler:
    use_batch_repeats: True

experiment:
  debug: False
  warm_start: ./ckpt/se3-fm/se3_vf_loss_rescaled/2023-09-20_05-48-51/last.ckpt
  num_devices: 1
  training:
    aux_loss_weight: 0.5
  wandb:
    name: auxiliary_losses
  trainer:
    accumulate_grad_batches: 4
