defaults:
  - base
  - _self_

data:
  sampler:
    max_batch_size: 32
    max_num_res_squared: 300_000

model:
  framediff:
    ipa:
      num_blocks: 8

experiment:
  debug: False
  num_devices: 4
  wandb:
    name: big_model
