defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 128
    min_num_res: 0
  sampler:
    max_batch_size: 100
    max_num_res_squared: 600_000

interpolant:
  trans:
    # corrupt: True
    pre_align: False # True
    batch_ot: True

experiment:
  debug: False

  num_devices: 2
  wandb:
    # name: scope_128_new_batching
    # name: scope_128_big_batch_2
    name: scope_128_warm_start_ot

  trainer:
    accumulate_grad_batches: 2
    check_val_every_n_epoch: 2

  warm_start: ./ckpt/se3-fm/scope_128_big_batch/2023-10-17_18-01-46/last.ckpt
  # warm_start: ./ckpt/se3-fm/scope_128_big_batch_2/2023-10-17_18-28-28/last.ckpt
  # warm_start: ./ckpt/se3-fm/refactor_with_align/2023-10-15_16-55-30/last.ckpt
