defaults:
  - base
  - _self_

data:
  dataset:
    # max_num_res: 256
    min_num_res: 0
  # loader:
  #   num_workers: 10
  #   prefetch_factor: 25
  sampler:
    max_num_res_squared: 500_000
    max_batch_size: 100
    # max_num_res_squared: 800_000
    use_batch_repeats: False

# model:
#   flow:
#     ipa:
#       num_blocks: 6

experiment:
  debug: False
  # so3_prior: uniform
  wandb:
    name: no_constant_scaling

  # sampling:
  #   vf_scaling: 1.0

  # training:
  #   aux_loss_weight: 1.0
  #   aux_loss_t_pass: 0.25

  # trainer:
  #   accumulate_grad_batches: 2
  #   check_val_every_n_epoch: 2

  # warm_start: ./ckpt/se3-fm/large_model/2023-09-30_15-47-47/epoch=244-step=241325.ckpt

  # trainer:
  #   accumulate_grad_batches: 4
  #   check_val_every_n_epoch: 5
