defaults:
  - base
  - _self_

data:
  sampler:
    max_batch_size: 64

model:
  architecture: flower

  flower:
    symmetric: True
    edge_features:
      use_rbf: True
      num_rbf: 48
    potential_network:
      num_blocks: 4
      edge_update:
        symmetric_update: True
        single_bias: True
        pair_transition_n: 1
      structure_update:
        seq_tfmr:
          enable: True

experiment:
  num_devices: 2
  debug: False
  trainer:
    accumulate_grad_batches: 1
  wandb:
    name: flower
    tags: ['experimental']