defaults:
  - base
  - _self_

data:
  sampler:
    max_batch_size: 32
    use_batch_repeats: False
    max_num_res_squared: 500_000

model:
  architecture: flower

  flower:
    symmetric: True
    edge_features:
      use_rbf: True
      num_rbf: 48
    potential_network:
      num_blocks: 4
      edge_update:
        symmetric_update: True
        single_bias: True

experiment:
  num_devices: 2
  debug: False
  trainer:
    accumulate_grad_batches: 2
  training:
    self_correcting: True
  wandb:
    name: flower
    tags: ['experimental']