defaults:
  - base
  - _self_

data:
  sampler:
    max_batch_size: 64

model:
  architecture: flower

  flower:
    symmetric: True
    edge_features:
      use_rbf: True
      num_rbf: 48
    potential_network:
      edge_update:
        symmetric_update: True

experiment:
  num_devices: 2 #1
  debug: False #True
  wandb:
    name: flower
    tags: ['experimental']