# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:

  name: eval

  # Use this to write with date-time stamp.
  #name: run_${now:%Y-%m-%d}_${now:%H-%M}

  overwrite: False
  seed: 123

  # https://wandb.ai/jyim/se3-fm/runs/owv79pn2 
  ckpt_path: ckpt/se3-fm/scope_256/2023-10-19_10-54-29/last.ckpt
  
  use_gpu: True
  num_gpus: 4

  interpolant:
    min_t: 1e-2
    provide_kappa: True
    rots:
      corrupt: True
      sample_schedule: exp
      exp_rate: 10
    trans:
      corrupt: True
      pre_align: True
      sample_schedule: linear
      sample_temp: 1.0
    sampling:
      num_timesteps: 100
      do_sde: False
    self_condition: True

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN
  output_dir: ./inference_outputs/

  write_to_wandb: True
  wandb:
    project: se3-fm-inference

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 60
    # Maximum sequence length to sample.
    max_length: 255
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 5
    overwrite: False
