# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - inference
  - _self_

inference:

  name: debug
  
  use_gpu: True
  num_gpus: 1

  samples:
    min_length: 60
    max_length: 61
    samples_per_length: 2
    seq_per_sample: 2
    length_step: 1
