# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:
  name: ddp_test
  seed: 123

  # https://wandb.ai/jyim/se3-fm/runs/0sfpo74r/overview
  # ckpt_path: ckpt/se3-fm/warm_start/2023-09-05_20-21-01/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/z0zlh0xs/overview
  # ckpt_path: ckpt/se3-fm/flower/2023-09-05_20-34-26/last.ckpt

  ckpt_path: '/data/rsg/chemistry/jyim/projects/flow-matching/ckpt/se3-fm/warm_start/2023-09-05_20-21-01/last.ckpt'
  
  use_gpu: True
  use_ca_pmpnn: True

  # Number of steps.
  num_timesteps: 100
  do_sde: False

  # DDP settings.
  num_gpus: 4
  batch_size_per_gpu: 4

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN
  output_dir: ./inference_outputs/

  wandb_enable: False
  wandb:
    project: se3-fm-inference
    tags: ['ts_${inference.num_timesteps}']

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 60 # 60
    # Maximum sequence length to sample.
    max_length: 64 # 128
