# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - inference
  - _self_

inference:
  name: dev

  # Number of steps.
  num_timesteps: 10

  wandb:
    tags: ['debug']

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 3
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 3
    # Minimum sequence length to sample.
    min_length: 60
    # Maximum sequence length to sample.
    max_length: 61
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 1
    overwrite: False
