# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:
  # name: run_${now:%Y-%m-%d}_${now:%H-%M-%S}
  overwrite: False
  seed: 123

  ckpt_path: ckpt/se3-fm/scope_128_warm_start_ot/2023-10-18_13-04-51/last.ckpt
  
  use_gpu: True

  # DDP settings.
  num_gpus: 4
  batch_size_per_gpu: 4

  interpolant:
    min_t: 1e-3
    rots:
      corrupt: True
      training_prior: null
      train_schedule: null
      sample_schedule: exp
      exp_rate: 10
      igso3_min_sigma: 0.1
      igso3_max_sigma: 1.5
    trans:
      corrupt: True
      pre_align: True
      train_schedule: null
      sample_schedule: linear
      sample_temp: 1.0
    sampling:
      num_timesteps: 100
      do_sde: False
    self_condition: True

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN
  output_dir: ./inference_outputs/

  wandb_enable: True
  wandb:
    project: se3-fm-inference

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 60
    # Maximum sequence length to sample.
    max_length: 128
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 1
    overwrite: False
