# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:
  name: null
  seed: 123

  # https://wandb.ai/jyim/se3-fm/runs/utm47hxa/overview
  ckpt_path: ckpt/se3-fm/warm_start/2023-10-01_16-54-48/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/qvqfzaj6/overview
  # ckpt_path: ckpt/se3-fm/warm_start_aux_loss/2023-10-01_17-04-33/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/dgd3bt3z
  # ckpt_path: ckpt/se3-fm/warm_start_aux_loss/2023-09-30_19-24-08/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/zhgmrkpx/overview
  # ckpt_path: ckpt/se3-fm/warm_start_batch_repeats/2023-09-30_15-52-15/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/m9fvhm52/overview
  # ckpt_path: ckpt/se3-fm/warm_start_self_cond_1/2023-09-30_19-03-53/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/z8rydc7e/overview
  # ckpt_path: ckpt/se3-fm/warm_start_self_condition_uniform/2023-09-29_14-57-36/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/q501fffp/overview
  # ckpt_path: ckpt/se3-fm/warm_start_self_condition/2023-09-29_14-34-20/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/gkllbijk/overview
  # ckpt_path: ckpt/se3-fm/warm_start_self_condition_faster/2023-09-29_14-38-40/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/jehepz92
  # ckpt_path: ckpt/se3-fm/baseline/2023-09-28_19-24-06/last.ckpt

  # https://wandb.ai/protein-diffusion/se3-fm/runs/0rx50arn/overview
  # ckpt_path: ckpt/se3-fm/baseline_faster/2023-09-23_08-04-04/last.ckpt

  # https://wandb.ai/protein-diffusion/se3-fm/runs/61noaiso
  # ckpt_path: ckpt/se3-fm/self_correcting/2023-09-20_22-38-33/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/vnftjmcn/overview
  # ckpt_path: ckpt/se3-fm/se3_vf_loss_rescaled/2023-09-20_05-48-51/last.ckpt  

  # https://wandb.ai/jyim/se3-fm/runs/0sfpo74r/overview
  # ckpt_path: ckpt/se3-fm/warm_start/2023-09-05_20-21-01/last.ckpt

  # https://wandb.ai/jyim/se3-fm/runs/z0zlh0xs/overview
  # ckpt_path: ckpt/se3-fm/flower/2023-09-05_20-34-26/last.ckpt
  
  use_gpu: True
  use_ca_pmpnn: False

  # Number of steps.
  num_timesteps: 10

  do_sde: False

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  pmpnn_dir: ./ProteinMPNN
  output_dir: ./inference_outputs/

  wandb_enable: True
  wandb:
    project: se3-fm-inference
    tags: [
      'ts_${inference.num_timesteps}',
      'ca_mpnn_${inference.use_ca_pmpnn}',
      'sde_${inference.do_sde}'
    ]

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 10
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 8
    # Minimum sequence length to sample.
    min_length: 60
    # Maximum sequence length to sample.
    max_length: 128
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 1
    overwrite: False
