defaults:
  - base
  - _self_

# model:
#   framediff:
#     use_rot_updates: False
#     predict_rot_vf: True

data:
  # CSV for path and metadata to training examples.
  dataset:
    min_num_res: 90
    subset: 100
  sampler:
    use_batch_repeats: True

experiment:
  noise_rots: True
  noise_trans: False
  debug: False
  batch_ot:
    enabled: False
  training:
    tanslaion_loss_weight: 0.0
    rotation_loss_weights: 1.0
    rotation_loss_clipping: 0.7
    bb_atom_loss_t_clip: 0.0
    bb_atom_scale: 0.1
  # warm_start: ./ckpt/se3-fm/only_noise_rots/2023-09-23_17-28-01/last.ckpt
  wandb:
    name: only_noise_rots_subset
    # name: only_noise_rots_subset_bb_atom_loss
    # name: only_noise_rots_subset_rots_separate_loss
    tags: ['only_rots']
