defaults:
  - base
  - _self_

model:
  framediff:
    use_rot_updates: False
    predict_rot_vf: True

data:
  # CSV for path and metadata to training examples.
  dataset:
    min_num_res: 90
    subset: 100
  sampler:
    use_batch_repeats: True

experiment:
  noise_rots: False
  noise_trans: True
  debug: False
  batch_ot:
    enabled: False
  training:
    rotation_loss_weights: 1.0
    rotation_loss_clipping: 0.7
    bb_atom_loss_t_clip: 0.7
    bb_atom_scale: 0.5
  # warm_start: ./ckpt/se3-fm/only_noise_rots/2023-09-23_17-28-01/last.ckpt
  wandb:
    name: only_noise_trans_subset
    tags: ['only_rots']
