defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 110
    min_num_res: 100
    subset: 10
  sampler:
    num_batches: 1000

experiment:
  debug: False
  wandb:
    name: overfit_subset_${data.dataset.subset}
    tags: ['overfit']
