defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 100
    min_num_res: 100
    subset: 2
  sampler:
    num_batches: 1000
    batch_repeats: 20
  loader:
    num_workers: 10
    prefetch_factor: 100

experiment:
  debug: False
  batch_ot:
    enabled: True
  wandb:
    name: overfit_subset_${data.dataset.subset}
    tags: ['overfit']
