defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 256
    spherical_motif_prob: 0.5
    contiguous_motif_prob: 0.5
  sampler:
    max_batch_size: 128
    max_num_res_squared: 1_000_000
    # max_batch_size: 100
    # max_num_res_squared: 500_000

model:
  node_features:
    embed_diffuse_mask: True
    separate_t: True

interpolant:
  separate_t: True
  # trans:
  #   train_schedule: vpsde
  #   sample_schedule: vpsde

experiment:
  debug: False

  warm_start_cfg_override: False

  num_devices: 2

  trainer:
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 2

  wandb:
    # name: scope_256_separate_t_vp
    # name: scope_256_separate_t_linear
    name: scope_256_scaffolding_v2
    # name: scope_256_separate_t

  warm_start: ckpt/se3-fm/scope_256_scaffolding_v2/2023-10-26_00-19-22/last.ckpt
  # warm_start: ckpt/se3-fm/scope_256_scaffolding/2023-10-24_21-13-38/last.ckpt
  # warm_start: ckpt/se3-fm/scope_256_separate_t_linear/2023-10-22_08-51-56/last.ckpt
  # warm_start: ckpt/se3-fm/scope_256_scaffolding/2023-10-23_19-49-31/last.ckpt
