defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 256
    motif_scaffold_prob: 0.0
  sampler:
    # max_batch_size: 128
    # max_num_res_squared: 1_000_000
    max_batch_size: 100
    max_num_res_squared: 500_000

model:
  node_features:
    embed_diffuse_mask: True
    separate_t: True

interpolant:
  separate_t: False

experiment:
  debug: False

  warm_start_cfg_override: False

  num_devices: 2

  trainer:
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 2

  wandb:
    name: scope_256_separate_t_linear
    # name: scope_256_scaffolding
    # name: scope_256_separate_t

  warm_start: ckpt/se3-fm/scope_256_separate_t_linear/2023-10-22_08-51-56/last.ckpt
  # warm_start: ckpt/se3-fm/scope_256_scaffolding/2023-10-23_19-49-31/last.ckpt
