defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 128
    min_num_res: 100
    subset: 100
  sampler:
    num_batches: 1000

experiment:
  debug: False
  wandb:
    name: subset_${data.dataset.subset}
    tags: ['subset']
