defaults:
  - base
  - _self_

data:
  dataset:
    max_num_res: 512
    min_num_res: 60
    spherical_motif_prob: 0.5
    contiguous_motif_prob: 0.5
    min_plddt_percent: 0.7
    max_coil_percent: 0.7
    csv_path: ./swiss_prot/swiss_prot_pkls/metadata.csv
  sampler:
    # max_batch_size: 100
    # max_num_res_squared: 500_000
    max_batch_size: 128
    max_num_res_squared: 1_000_000

model:
  node_features:
    embed_diffuse_mask: True
    separate_t: True

interpolant:
  separate_t: False

experiment:
  debug: False

  warm_start_cfg_override: False

  num_devices: 4
  wandb:
    # name: swiss_prot_scaffolding_linear_t
    name: swiss_prot_scaffolding_v2

  trainer:
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  
  checkpointer:
    every_n_epochs: null
    every_n_train_steps: 10000

  training:
    min_plddt_mask: 0.8

  warm_start: ckpt/se3-fm/swiss_prot_scaffolding_v2/2023-10-26_00-22-17/last.ckpt
  # warm_start: ckpt/se3-fm/swiss_prot_scaffolding/2023-10-25_08-43-27/last.ckpt
  # warm_start: ckpt/se3-fm/swiss_prot_separate_t_linear/2023-10-23_20-05-39/last.ckpt
  # warm_start: ckpt/se3-fm/swiss_prot_scaffolding/2023-10-23_20-07-00/last.ckpt
